# original found on https://gist.github.com/CyanAutomation/1b8bafd033f73e3c24e42e8f381ff906
blueprint:
  name: Lights On At Sunset
  description: Turn on the following lights shortly after sunset
  domain: automation
  input:
    # Create a variable for identifying the light to act upon
    target_light:
      name: Lights
      description: This is the light (or lights) that will be activated at sunset
      # Use a selector, to pick the light(s)
      selector:
        target:
          entity:
            domain: light
    # Create a variable for capturing the desired brightness of the activated lights
    target_brightness:
      name: Brightness
      description: Brightness of the light(s) when they're activated
      default: 40
      # Use a selector, to set the brightness
      selector:
        number:
          min: 5
          max: 100
          mode: slider
          step: 5
          unit_of_measurement: "%"
# Prevent the automation from running concurrently
mode: single

# Define the variables used in the action section
variables:
  target_brightness: !input target_brightness
  target_light: !input target_light

# Define the trigger for the automation
trigger:
  platform: numeric_state
  entity_id: sun.sun
  value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
  below: -1

# This section will take action on the lights, and turn them on
action:
  # A very simple structure of turning on the selected light(s)
  - service: light.turn_on
    target: !input target_light
    # Set and pass the desired brightness
    data_template:
      brightness_pct: "{{ target_brightness | int }}"
